# Generated by Django 5.1.4 on 2024-12-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
