# Generated by Django 5.1.4 on 2024-12-26 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postos', '0002_mapa_titulo_alter_mapa_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='titulo',
        ),
        migrations.AddField(
            model_name='mapa',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='mapas/'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.mapa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
